services:
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:v1.84.3
    env_file:
      - "/home/docker/env/tailscale/.env"
    volumes:
      - tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    restart: unless-stopped



volumes:
  tailscale-state:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.7,nfsvers=4"
      device: ":/mnt/store-0/service_storage/zd/tailscale/state"
